### ISSUE TITLE
what's the use case of such ir

### ISSUE THREAD

**Issue by bobzhang** [alibaba/xoc#5]
is it optimized for dynamic language? or like llvm ir, by reading the readme file, it is not clear to me

**Comment by stevenknown** [comment]
Hi, Hongbo, Sorry for the obscure readme, there is a preliminary
manual under doc/ describing the IR syntax and sematics.

In a simple word, XOC IR is designed for both static and dynamic
language,  since XOC infrastructure is capable of processing the both.
I think it will be more powerful than LLVM ir ;).

For example, we implement an AOT optimizer based on XOC for Android,
says, optimizing DEX code, this is a scenarios of static language. And
a Type Infer Module also based on XOC for JavaScript, that is a
scenarios of dynamic language.

I hope this information is useful for you :)

Steven

2016-02-17 0:38 GMT+08:00, Hongbo Zhang notifications@github.com:
